# -*- coding: utf-8 -*-
# Copyright: 2015,2016 Bastian Blank
# License: MIT, see LICENSE for details.

---
- name: Create SSH key certificates
  action:
    module: sshcert
    args:
      signkey: "{{ signkey }}"
      pubkey: "{{ dir }}/ssh_host_{{ item }}_key.pub"
      cert: "{{ dir }}/ssh_host_{{ item }}_key-cert.pub"
      cert_id: "{{ cert_id }}"
      cert_names: "{{ cert_names }}"
      cert_resign: "{{ cert_resign }}"
      cert_valid: "{{ cert_valid }}"
  with_items: "{{ key_types }}"
